### ISSUE TITLE
[BUG]A Potential Bug of Use of Uninitialized Variable

### ISSUE THREAD

**Issue by Hyxl1017** [zeroc-ice/mcpp#6]
Hello,I found a potential bugs of Use of Uninitialized Variable in source code of mcpp,would you help me check if this bugs is true?thanks for your patience and effort.

==============================================================================

step  1 : 
	 In file  mcpp/mbchar.c , function  mb_read_utf8  [line  160](https://github.com/zeroc-ice/mcpp/blob/master/mbchar.c#L160):
 		 bytes is defined here but uninitialized.

step  2 : 
	 In file  mcpp/mbchar.c , function  mb_read_utf8   [line  160](https://github.com/zeroc-ice/mcpp/blob/master/mbchar.c#L162):
 		 An uninitialized value reaches here 

step  3 : 
	 In file  mcpp/mbchar.c , function  mb_read_utf8   [line  166](https://github.com/zeroc-ice/mcpp/blob/master/mbchar.c#L166) :
 		 Select the false branch at this point ((char_type[ c1 & UCHARMAX] & U2_1) == U2_1 is false) (namely, all if-branch is false)

step  4 : 
	 In file  mcpp/mbchar.c , function  mb_read_utf8   [line  170](https://github.com/zeroc-ice/mcpp/blob/master/mbchar.c#L170):
 		 bytes is used in the arithmetic operation but bytes is not initialized 

==============================================================================

**Comment by pepone** [comment]
https://github.com/zeroc-ice/mcpp/blob/e6abf9a561294b667bb931b80cf749c9be2d1a2f/mbchar.c#L166-L167

The `if` part is commented out the code should enter the else block and the `bytes` variable would be initialized to `2`

**Comment by Hyxl1017** [comment]
> https://github.com/zeroc-ice/mcpp/blob/e6abf9a561294b667bb931b80cf749c9be2d1a2f/mbchar.c#L166-L167
> 
> The `if` part is commented out the code should enter the else block and the `bytes` variable would be initialized to `2`

OK, I didn't notice that this part of the code has been commented out and this old bug has been fixed. Thank you very much for your reply.
