### ISSUE TITLE
how mcpp support sourcemap

### ISSUE THREAD

**Issue by alonWang** [zeroc-ice/mcpp#7]
I'm a beginner in this.  
I know that mcpp handle include&macro&define  but how to maintain the relationship of original source code and the proceed code?
does mcpp have such support?
(ignore if it's meaningless.

**Comment by pepone** [comment]
Hi @alonWang 

This is out of the scope of this repo, which is a fork of mcpp to build [zeroc-ice/ice](https://github.com/zeroc-ice/ice).

If I recall correctly mcpp emits info about the files being processed along with the output, but best check the mcpp output.
